### ISSUE TITLE
HP DL360 with failing dimms gets HTTP 500 error

### ISSUE THREAD

**Issue by brad-marshall** [sapcc/redfish-exporter#8]
I have some systems with failed dimms that are getting a 500 error from the redfish exporter when being scraped, and we get the following errors in the logs:

2024-02-29 22:31:19 [FALCON] [ERROR] GET /health?job=redfish%2Fhardware&target=redacted => Traceback (most recent call last):
   File "falcon/app.py", line 365, in falcon.app.App.__call__
   File "/redfish_exporter/handler.py", line 103, in on_get
     resp.body = generate_latest(registry)
   File "/usr/local/lib/python3.10/dist-packages/prometheus_client/exposition.py", line 251, in generate_latest
     for metric in registry.collect():
   File "/redfish_exporter/collector.py", line 361, in collect
     metrics.collect()
   File "/redfish_exporter/collectors/health_collector.py", line 369, in collect
     self.get_memory_health()
   File "/redfish_exporter/collectors/health_collector.py", line 256, in get_memory_health
     if type(dimm_info["Status"]) == str:
 KeyError: 'Status'

This causes no data to be returned at all for the host.  The ilo firmwares are currently downrev, I'll see what I can do about getting them upgraded to see if that helps.

**Comment by baonq-me** [comment]
@brad-marshall Do you have sample response data ?

**Comment by BerndKue** [comment]
Not sure if this is still an issue. I did some major code changes since then including generalizing the way the status of a component is getting pulled. Looking at the code, I guess this should no longer cause an exception.

Please reopen if you still are facing the issue.
